### PR TITLE
Add Host Photos to DB/Data Seed

### PR DESCRIPTION
**Pull request by glindelien**
Hey @Alex-Coplin ! I modified my Schema and dataSeed files to include random user profile photos for the hosts. These will be displayed on the front-end next to the title.

**Title.jsx** - added photo to title component
**index.jsx** - added photo to State via GET request when components mount
**dataSeed** - created hostPhotos array to add into DB when this file runs
**schema.sql** - added a field for the photo in the Listings table

### CODE REVIEW

**Comment by Alex-Coplin** [comment]
Looks good!

**Review by ryancmoniz — COMMENTED** [review]
I was initially going to comment "Can we generate these host photos programmatically?", but you ended up changing that in a later commit, awesome!. Let's remember not to commit our bundle.js file. This file is generated by webpack and doesn't need to exist on github. Also, remember to handle your errors correctly. It looks like your database is currently just logging an error if something bad happens. We want to handle that error all the way up to the server so an end user can know something went wrong. Otherwise, LGTM!

**Comment by glindelien** [comment]
@ryancmoniz thank you for the feedback! Will be sure to stop committing my bundle :P

re: error handling - are you referring to the if (err) console.log(err) in my dataSeed.js file? This file was just used for data seeding purposes and doesn't go through my server at all, so the console logs are just for me to see in the terminal during the seeding process. Otherwise, in my back-end server routes & query handlers, I'm using the error-first callback pattern to pass errors to the callbacks (which are then executed server-side). If the server receives an error from the DB query, it executes res.sendStatus(500).

Let me know if I should be doing something differently there :)

Examples:

Server route
`app.get('/listing/:id/info', (req, res) => {
  query.getListingByID(req.params.id, (err, data) => {
    if (err) {
      res.sendStatus(500);
    } else {
      res.send(data);
    }
  });
});`

query handler
`getListingByID: function (id, callback) {
    let queryStr = `SELECT * FROM listings WHERE (ID = ${id})`;
    db.query(queryStr, (err, data) => {
      if (err) {
        callback(err, null);
      } else {
        callback(null, data);
      }
    });
  }`

**Comment by ryancmoniz** [comment]
Generally, you want to send _something_ back with your error status. In something like this we can just send a string like "Error: Could not retrieve listing from Database", or something similar so a user knows "Its not you, it's me!". Otherwise, my postman is just going to say Internal Server Error and I will be like "Hmmm, maybe if I refresh and try again?". The pattern you are using is correct though!

**Pull request merged**
